const usaMapTable = {
  ids: ["hi", "ak", "fl", "sc"],
  entities: {
    hi: {
      id: "hi",
      owner: "",
      troopsCount: 0,
      neighbours: ["ak", "tx"],
    },
    ak: {
      id: "ak",
      owner: "",
      troopsCount: 0,
      neighbours: ["hi", "ca", "az"],
    },
    fl: {
      id: "fl",
      owner: "",
      troopsCount: 0,
      neighbours: ["ga", "al", "pr"],
    },
    sc: {
      id: "sc",
      owner: "",
      troopsCount: 0,
      neighbours: ["ga", "nc"],
    },
    ga: {
      id: "ga",
      owner: "",
      troopsCount: 0,
      neighbours: ["fl", "sc", "al", "nc", "tn"],
    },
    al: {
      id: "al",
      owner: "",
      troopsCount: 0,
      neighbours: ["fl", "ga", "tn", "ms"],
    },
    nc: {
      id: "nc",
      owner: "",
      troopsCount: 0,
      neighbours: ["sc", "tn", "va"],
    },
    tn: {
      id: "tn",
      owner: "",
      troopsCount: 0,
      neighbours: ["ga", "al", "nc", "ky", "ms", "mo", "ar", "va"],
    },
    nn: {
      id: "nn",
      owner: "",
      troopsCount: 0,
      neighbours: ["ma"],
    },
    ma: {
      id: "ma",
      owner: "",
      troopsCount: 0,
      neighbours: ["nn", "wv", "oh", "mi", "va"],
    },
    wv: {
      id: "wv",
      owner: "",
      troopsCount: 0,
      neighbours: ["ma", "ky", "oh", "va"],
    },
    ky: {
      id: "ky",
      owner: "",
      troopsCount: 0,
      neighbours: ["tn", "wv", "oh", "in", "il", "mo", "va"],
    },
    oh: {
      id: "oh",
      owner: "",
      troopsCount: 0,
      neighbours: ["ma", "wv", "ky", "mi", "in"],
    },
    mi: {
      id: "mi",
      owner: "",
      troopsCount: 0,
      neighbours: ["ma", "oh", "in", "il", "mn", "wi"],
    },
    mt: {
      id: "mt",
      owner: "",
      troopsCount: 0,
      neighbours: ["id", "nd", "sd", "wy"],
    },
    id: {
      id: "id",
      owner: "",
      troopsCount: 0,
      neighbours: ["mt", "nv", "ut", "or", "wa", "wy"],
    },
    tx: {
      id: "tx",
      owner: "",
      troopsCount: 0,
      neighbours: ["hi", "nm", "ar", "ok", "la"],
    },
    ca: {
      id: "ca",
      owner: "",
      troopsCount: 0,
      neighbours: ["ak", "az", "nv", "or"],
    },
    az: {
      id: "az",
      owner: "",
      troopsCount: 0,
      neighbours: ["ak", "ca", "nv", "ut", "nm"],
    },
    nv: {
      id: "nv",
      owner: "",
      troopsCount: 0,
      neighbours: ["id", "ca", "az", "ut", "or"],
    },
    ut: {
      id: "ut",
      owner: "",
      troopsCount: 0,
      neighbours: ["id", "az", "nv", "co", "wy"],
    },
    co: {
      id: "co",
      owner: "",
      troopsCount: 0,
      neighbours: ["ut", "nm", "ne", "ok", "ks", "wy"],
    },
    nm: {
      id: "nm",
      owner: "",
      troopsCount: 0,
      neighbours: ["tx", "az", "co", "ok"],
    },
    or: {
      id: "or",
      owner: "",
      troopsCount: 0,
      neighbours: ["id", "ca", "nv", "wa"],
    },
    nd: {
      id: "nd",
      owner: "",
      troopsCount: 0,
      neighbours: ["mt", "sd", "mn"],
    },
    sd: {
      id: "sd",
      owner: "",
      troopsCount: 0,
      neighbours: ["mt", "nd", "ne", "ia", "mn", "wy"],
    },
    ne: {
      id: "ne",
      owner: "",
      troopsCount: 0,
      neighbours: ["co", "sd", "ia", "mo", "ks", "wy"],
    },
    ia: {
      id: "ia",
      owner: "",
      troopsCount: 0,
      neighbours: ["sd", "ne", "il", "mn", "wi", "mo"],
    },
    ms: {
      id: "ms",
      owner: "",
      troopsCount: 0,
      neighbours: ["al", "tn", "ar", "la"],
    },
    in: {
      id: "in",
      owner: "",
      troopsCount: 0,
      neighbours: ["ky", "oh", "mi", "il", "wi"],
    },
    il: {
      id: "il",
      owner: "",
      troopsCount: 0,
      neighbours: ["ky", "mi", "ia", "in", "wi", "mo"],
    },
    mn: {
      id: "mn",
      owner: "",
      troopsCount: 0,
      neighbours: ["mi", "nd", "sd", "ia", "wi"],
    },
    wi: {
      id: "wi",
      owner: "",
      troopsCount: 0,
      neighbours: ["mi", "ia", "in", "il", "mn"],
    },
    mo: {
      id: "mo",
      owner: "",
      troopsCount: 0,
      neighbours: ["tn", "ky", "ne", "ia", "il", "ar", "ok", "ks"],
    },
    ar: {
      id: "ar",
      owner: "",
      troopsCount: 0,
      neighbours: ["tn", "ms", "ok", "mo", "la"],
    },
    ok: {
      id: "ok",
      owner: "",
      troopsCount: 0,
      neighbours: ["tx", "co", "nm", "mo", "ar", "ks"],
    },
    ks: {
      id: "ks",
      owner: "",
      troopsCount: 0,
      neighbours: ["co", "ne", "mo", "ok"],
    },
    la: {
      id: "la",
      owner: "",
      troopsCount: 0,
      neighbours: ["tx", "ms", "ar"],
    },
    va: {
      id: "va",
      owner: "",
      troopsCount: 0,
      neighbours: ["nc", "tn", "ma", "wv", "ky"],
    },
    wa: {
      id: "wa",
      owner: "",
      troopsCount: 0,
      neighbours: ["id", "or"],
    },
    wy: {
      id: "wy",
      owner: "",
      troopsCount: 0,
      neighbours: ['mt', "id", "ut", 'co', 'sd', 'ne'],
    },
    pr: {
      id: "pr",
      owner: "",
      troopsCount: 0,
      neighbours: ["fl"],
    },
  },
};

usaMapTable.ids = Object.keys(usaMapTable.entities).slice();

export {usaMapTable};